version: "3"
services:
  es01:
    image: elasticsearch:7.1.1
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - TZ=Asia/Shanghai
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./node/es01/data:/usr/share/elasticsearch/data
      - ./node/es01/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./plugins:/usr/share/elasticsearch/plugins
    restart: always
    container_name: es01

  es02:
    image: elasticsearch:7.1.1
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - TZ=Asia/Shanghai
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./node/es02/data:/usr/share/elasticsearch/data
      - ./node/es02/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./plugins:/usr/share/elasticsearch/plugins
    restart: always
    container_name: es02

  kibana:
    image: kibana:7.1.1
    ports:
      - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/etc/kibana/kibana.yml
    links:
      - es01:elasticsearch
    container_name: kibana